module.exports={
    dbfile:"timesheets.db",
    emails:["@domain.com"],
    secret:"changethissecretandkeepitprotected",
    port:8080,
    websocket:true,
    maxupload:100*1024*1024,
    uploadDirectory:"uploads",
    useTempFiles:false,
    tempFileDir:"temp"
}