module.exports={
    dbfile:"timesheets.db",
    emails:["@vinci.be","@student.vinci.be"],
    secret:"CXOM8DezKRyOsmk2zVQbddggyyuiAZN",
    port:8080,
    websocket:true,
    maxupload:100*1024*1024,
    uploadDirectory:"uploads",
    useTempFiles:false,
    tempFileDir:"temp"
}
